version: '3'

services:
        redis:
                image: redis
        bot:
                build: .
                volumes:
                        - 'mafs:/user/app/src/data'
                env_file:
                        - .env
                depends_on:
                        - redis


volumes:
        mafs:
